#!/usr/bin/env python3
"""sre-oncall corpus build driver.

Registers the sre-oncall bespoke renderers into the compiler registry, then
runs the Gold Compiler's real machinery (verify -> synthesize) against
tables.jsonl with the manual.md as the verbatim source and sre_oncall/anchors
as the human-in-loop anchors. Standalone: does not modify corpus.py.

Usage: python3 research/compiler/sre_oncall/build.py [--out DIR]
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]  # repo root
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from research.compiler import (
    core,
    corpus,
    renderers,
)
from research.compiler.sre_oncall import anchors as _anchors
from research.compiler.sre_oncall import renderers as _my_rend

# Deterministic split assignment with STRICT GROUP SEPARATION: each decision
# (source_group_id) lands in exactly one split, so nothing a head learns in
# training bleeds into what the ECE gate evaluates. train.py trains ONLY on the
# 'train' split and gates ECE on boolean rows in BOTH 'test' and 'ood'
# (threshold 0.20). So we need boolean decisions in train (to LEARN boolean
# calibration) AND in test AND in ood (to gate it) — 4 boolean decisions
# available, one per role.
SPLIT_PLAN = {
    # choice decisions -> train (the bulk the head learns)
    "severity-class": "train",
    "fix-posture": "train",
    "comms-escalation": "train",
    # boolean decisions — TWO in train so the head learns a richer boolean
    # family (the first run's test failure was narrow boolean generalization
    # from a single trained boolean), one each for the untouchable gates.
    "force-restart": "train",          # boolean in train  -> learn booleans
    "log-ci-verdict": "train",         # boolean in train  -> learn booleans
    "page-second-responder": "test",   # boolean in test   -> ECE gate coverage
    "canary-promote": "ood",           # boolean in ood    -> ECE gate coverage
}

HERE = Path(__file__).resolve().parent

_EXTRA_RENDERERS_DIR = HERE / "renderers"
_EXTRA_SPLITS_FILE = HERE / "splits.json"


def _extra_split_plan() -> dict:
    """Decision_id -> split for decisions added via new_decision.py. Merged over
    SPLIT_PLAN so autogenerated decisions train without editing this file."""
    if _EXTRA_SPLITS_FILE.is_file():
        try:
            return json.loads(_EXTRA_SPLITS_FILE.read_text() or "{}")
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def _register_renderers():
    for did, fn in _my_rend.RENDER.items():
        renderers.register("sre-oncall", did, fn)
    # auto-discover drop-in renderer modules written by new_decision.py:
    # renderers/<func>.py defining <func>(decision_id, st) -> list[str].
    if _EXTRA_RENDERERS_DIR.is_dir():
        import importlib.util
        for mod_file in sorted(_EXTRA_RENDERERS_DIR.glob("*.py")):
            if mod_file.name.startswith("_"):
                continue
            stem = mod_file.stem
            spec = importlib.util.spec_from_file_location(f"_sre_auto_{stem}", mod_file)
            if not spec or not spec.loader:
                continue
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            fn = getattr(module, stem, None)
            did = getattr(module, "DECISION_ID", stem)
            if callable(fn):
                # DecisionID is carried by the module itself (hyphenated, matching
                # the table); the file stem is just the snake_case function name.
                renderers.register("sre-oncall", did, fn)

def _load():
    tables = []
    for line in (HERE / "tables.jsonl").read_text().splitlines():
        if line.strip():
            t = json.loads(line)
            if not t.get("canonical_hash"):
                t["canonical_hash"] = corpus.canonical_hash(t)
            tables.append(t)
    return tables

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(HERE / "out"))
    args = ap.parse_args()
    out = Path(args.out); out.mkdir(parents=True, exist_ok=True)

    _register_renderers()
    tables = _load()
    manual = (HERE / "manual.md").read_text()

    # verify
    verified, flagged = [], []
    for t in tables:
        a = _anchors.anchors_for(t["decision_id"])
        rep = core.verify(t, anchors=a, source_text=manual)
        t["verification"] = rep["status"]
        for r in rep["per_rule"].values():
            print(f"  {t['decision_id']:<22} {r['verdict']:>12} anchors={r['anchors_covered']}")
        (verified if rep["status"] == "verified" else flagged).append(t)
    _write(out, "tables.verified.jsonl", verified + flagged)

    # synthesize
    split_plan = {**SPLIT_PLAN, **_extra_split_plan()}
    rows = []
    for t in verified:
        fid = f"{t['skill']}-{t['decision_id']}"
        split = split_plan.get(t["decision_id"], "train")
        rows.extend(core.make_rows(t, split, fid, 17))
    ordered = sorted(rows, key=lambda r: r["id"])
    p = _write(out, "train.jsonl", ordered)
    import hashlib
    sha = hashlib.sha256(p.read_bytes()).hexdigest()
    _write(out, "train.meta.json", [{"rows": len(ordered), "data_sha256": f"sha256:{sha}"}])
    print(f"verified={len(verified)} flagged={len(flagged)} rows={len(ordered)}")
    print(f"data_sha256=sha256:{sha}  file={p}")
    return 0 if not flagged else 3

def _write(out: Path, name: str, objs) -> Path:
    blob = "".join(json.dumps(o, ensure_ascii=False, sort_keys=True) + "\n" for o in objs)
    p = out / name
    p.write_text(blob, encoding="utf-8")
    return p

if __name__ == "__main__":
    sys.exit(main())